//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wnmp.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wnmp.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许Root远程访问 的本地化字符串。
        /// </summary>
        public static string ALLOW_REMOTE_ROOT_ACCESS {
            get {
                return ResourceManager.GetString("ALLOW_REMOTE_ROOT_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在运行 的本地化字符串。
        /// </summary>
        public static string ALREADY_RUNNING {
            get {
                return ResourceManager.GetString("ALREADY_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用程序 的本地化字符串。
        /// </summary>
        public static string APPLICATION {
            get {
                return ResourceManager.GetString("APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用程序设置 的本地化字符串。
        /// </summary>
        public static string APPLICATION_SETTINGS {
            get {
                return ResourceManager.GetString("APPLICATION_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用程序 的本地化字符串。
        /// </summary>
        public static string APPLICATIONS {
            get {
                return ResourceManager.GetString("APPLICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动检测更新 的本地化字符串。
        /// </summary>
        public static string AUTOMATICALLY_CHECK_FOR_UPDATES {
            get {
                return ResourceManager.GetString("AUTOMATICALLY_CHECK_FOR_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备份 的本地化字符串。
        /// </summary>
        public static string BACKED_UP {
            get {
                return ResourceManager.GetString("BACKED_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        public static string CHECK_FOR_UPDATES {
            get {
                return ResourceManager.GetString("CHECK_FOR_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 社区支持 的本地化字符串。
        /// </summary>
        public static string COMMUNITY_SUPPORT {
            get {
                return ResourceManager.GetString("COMMUNITY_SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置 的本地化字符串。
        /// </summary>
        public static string CONFIGURATION {
            get {
                return ResourceManager.GetString("CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;复制 的本地化字符串。
        /// </summary>
        public static string COPY {
            get {
                return ResourceManager.GetString("COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright (c) 2012 - {CURRENTYEAR} by Kurt Cancemi 的本地化字符串。
        /// </summary>
        public static string COPYRIGHT_TEXT {
            get {
                return ResourceManager.GetString("COPYRIGHT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法读取更新信息 的本地化字符串。
        /// </summary>
        public static string COULDNT_READ_UPDATE_INFORMATION {
            get {
                return ResourceManager.GetString("COULDNT_READ_UPDATE_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 捐献 的本地化字符串。
        /// </summary>
        public static string DONATE {
            get {
                return ResourceManager.GetString("DONATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载，请稍候... 的本地化字符串。
        /// </summary>
        public static string DOWNLOAD_IN_PROGRESS_PLEASE_WAIT {
            get {
                return ResourceManager.GetString("DOWNLOAD_IN_PROGRESS_PLEASE_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载更新... 的本地化字符串。
        /// </summary>
        public static string DOWNLOADING_UPDATE {
            get {
                return ResourceManager.GetString("DOWNLOADING_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑器 的本地化字符串。
        /// </summary>
        public static string EDITOR {
            get {
                return ResourceManager.GetString("EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;文件 的本地化字符串。
        /// </summary>
        public static string FILE_MENU {
            get {
                return ResourceManager.GetString("FILE_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规 的本地化字符串。
        /// </summary>
        public static string GENERAL {
            get {
                return ResourceManager.GetString("GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成的SSL密钥对 的本地化字符串。
        /// </summary>
        public static string GENERATED_SSL_KEYPAIR {
            get {
                return ResourceManager.GetString("GENERATED_SSL_KEYPAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取标题 的本地化字符串。
        /// </summary>
        public static string GET_HEADERS {
            get {
                return ResourceManager.GetString("GET_HEADERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取HTTP头 的本地化字符串。
        /// </summary>
        public static string GET_HTTP_HEADERS {
            get {
                return ResourceManager.GetString("GET_HTTP_HEADERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        public static string HEADER {
            get {
                return ResourceManager.GetString("HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;帮助 的本地化字符串。
        /// </summary>
        public static string HELP_MENU {
            get {
                return ResourceManager.GetString("HELP_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主机： 的本地化字符串。
        /// </summary>
        public static string HOST_SC {
            get {
                return ResourceManager.GetString("HOST_SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主机到IP： 的本地化字符串。
        /// </summary>
        public static string HOST_TO_IP {
            get {
                return ResourceManager.GetString("HOST_TO_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化控制面板 的本地化字符串。
        /// </summary>
        public static string INITIALIZING_CONTROL_PANEL {
            get {
                return ResourceManager.GetString("INITIALIZING_CONTROL_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的密码格式 的本地化字符串。
        /// </summary>
        public static string INVALID_PASSWORD_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP(s) 的本地化字符串。
        /// </summary>
        public static string IP_S {
            get {
                return ResourceManager.GetString("IP_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新版本： 的本地化字符串。
        /// </summary>
        public static string LATEST_VERSION_SC {
            get {
                return ResourceManager.GetString("LATEST_VERSION_SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 许可证 的本地化字符串。
        /// </summary>
        public static string LICENSE {
            get {
                return ResourceManager.GetString("LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        public static string LOGS {
            get {
                return ResourceManager.GetString("LOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MariaDB数据目录 &apos;{dataDirectory}&apos; 已存在，如果继续安装，将删除该目录。在此之前，您不希望丢失存在此目录中的任何数据，请备份。确定要继续吗？ 的本地化字符串。
        /// </summary>
        public static string MARIADB_DATA_DIR_EXISTS {
            get {
                return ResourceManager.GetString("MARIADB_DATA_DIR_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MariaDB设置 的本地化字符串。
        /// </summary>
        public static string MARIADB_SETUP {
            get {
                return ResourceManager.GetString("MARIADB_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MariaDB版本： 的本地化字符串。
        /// </summary>
        public static string MARIADB_VERSION {
            get {
                return ResourceManager.GetString("MARIADB_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小化到托盘 的本地化字符串。
        /// </summary>
        public static string MINIMIZE_TO_TRAY {
            get {
                return ResourceManager.GetString("MINIMIZE_TO_TRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小化到托盘，而不是关闭 的本地化字符串。
        /// </summary>
        public static string MINIMIZE_TO_TRAY_INSTEAD_OF_CLOSING {
            get {
                return ResourceManager.GetString("MINIMIZE_TO_TRAY_INSTEAD_OF_CLOSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动 的本地化字符串。
        /// </summary>
        public static string MOVED {
            get {
                return ResourceManager.GetString("MOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新版本！ 的本地化字符串。
        /// </summary>
        public static string NEW_VERSION_FOUND_EX {
            get {
                return ResourceManager.GetString("NEW_VERSION_FOUND_EX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nginx版本： 的本地化字符串。
        /// </summary>
        public static string NGINX_VERSION {
            get {
                return ResourceManager.GetString("NGINX_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未运行 的本地化字符串。
        /// </summary>
        public static string NOT_RUNNING {
            get {
                return ResourceManager.GetString("NOT_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开MariaDB Shell 的本地化字符串。
        /// </summary>
        public static string OPEN_MARIADB_SHELL {
            get {
                return ResourceManager.GetString("OPEN_MARIADB_SHELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项 的本地化字符串。
        /// </summary>
        public static string OPTIONS {
            get {
                return ResourceManager.GetString("OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空或包含空格。 的本地化字符串。
        /// </summary>
        public static string PASSWORD_CREATE_INVALID {
            get {
                return ResourceManager.GetString("PASSWORD_CREATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PHP扩展 的本地化字符串。
        /// </summary>
        public static string PHP_EXTENSIONS {
            get {
                return ResourceManager.GetString("PHP_EXTENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PHP 端口： 的本地化字符串。
        /// </summary>
        public static string PHP_PORT {
            get {
                return ResourceManager.GetString("PHP_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PHP 进程： 的本地化字符串。
        /// </summary>
        public static string PHP_PROCESSES {
            get {
                return ResourceManager.GetString("PHP_PROCESSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PHP版本： 的本地化字符串。
        /// </summary>
        public static string PHP_VERSION {
            get {
                return ResourceManager.GetString("PHP_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报告错误 的本地化字符串。
        /// </summary>
        public static string REPORT_BUG {
            get {
                return ResourceManager.GetString("REPORT_BUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启 的本地化字符串。
        /// </summary>
        public static string RESTART {
            get {
                return ResourceManager.GetString("RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启过去式 的本地化字符串。
        /// </summary>
        public static string RESTARTED {
            get {
                return ResourceManager.GetString("RESTARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root密码： 的本地化字符串。
        /// </summary>
        public static string ROOT_PASSWORD {
            get {
                return ResourceManager.GetString("ROOT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行状态 的本地化字符串。
        /// </summary>
        public static string RUNNING {
            get {
                return ResourceManager.GetString("RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择一个文本编辑器 的本地化字符串。
        /// </summary>
        public static string SELECT_A_TEXT_EDITOR {
            get {
                return ResourceManager.GetString("SELECT_A_TEXT_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置MariaDB 的本地化字符串。
        /// </summary>
        public static string SETUP_MARIADB {
            get {
                return ResourceManager.GetString("SETUP_MARIADB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        public static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动全部 的本地化字符串。
        /// </summary>
        public static string START_ALL {
            get {
                return ResourceManager.GetString("START_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开软件即启动MariaDB 的本地化字符串。
        /// </summary>
        public static string START_MARIADB_ON_LAUNCH {
            get {
                return ResourceManager.GetString("START_MARIADB_ON_LAUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开软件即启动Nginx 的本地化字符串。
        /// </summary>
        public static string START_NGINX_ON_LAUNCH {
            get {
                return ResourceManager.GetString("START_NGINX_ON_LAUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开软件即启动PHP 的本地化字符串。
        /// </summary>
        public static string START_PHP_ON_LAUNCH {
            get {
                return ResourceManager.GetString("START_PHP_ON_LAUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动Wnmp最小化 的本地化字符串。
        /// </summary>
        public static string START_WNMP_MINIMIZED {
            get {
                return ResourceManager.GetString("START_WNMP_MINIMIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开机自启 的本地化字符串。
        /// </summary>
        public static string START_WNMP_WITH_WINDOWS {
            get {
                return ResourceManager.GetString("START_WNMP_WITH_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        public static string STARTED {
            get {
                return ResourceManager.GetString("STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开MariaDB shell 的本地化字符串。
        /// </summary>
        public static string STARTED_MARIADB_SHELL {
            get {
                return ResourceManager.GetString("STARTED_MARIADB_SHELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string STOP {
            get {
                return ResourceManager.GetString("STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部停止 的本地化字符串。
        /// </summary>
        public static string STOP_ALL {
            get {
                return ResourceManager.GetString("STOP_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string STOPPED {
            get {
                return ResourceManager.GetString("STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;工具 的本地化字符串。
        /// </summary>
        public static string TOOLS_MENU {
            get {
                return ResourceManager.GetString("TOOLS_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新检查间隔(以天为单位) 的本地化字符串。
        /// </summary>
        public static string UPDATE_CHECK_INTERVAL_IN_DAYS {
            get {
                return ResourceManager.GetString("UPDATE_CHECK_INTERVAL_IN_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        public static string VALUE {
            get {
                return ResourceManager.GetString("VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        public static string VERSION {
            get {
                return ResourceManager.GetString("VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看更改日志 的本地化字符串。
        /// </summary>
        public static string VIEW_CHANGELOG {
            get {
                return ResourceManager.GetString("VIEW_CHANGELOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示 的本地化字符串。
        /// </summary>
        public static string VISIBLE {
            get {
                return ResourceManager.GetString("VISIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 官网 的本地化字符串。
        /// </summary>
        public static string WEBSITE {
            get {
                return ResourceManager.GetString("WEBSITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wnmp控制面板 的本地化字符串。
        /// </summary>
        public static string WNMP_CONTROL_PANEL {
            get {
                return ResourceManager.GetString("WNMP_CONTROL_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wnmp是一个简单的Windows、Nginx、MariaDB和PHP环境。 的本地化字符串。
        /// </summary>
        public static string WNMP_DESCRIPTION {
            get {
                return ResourceManager.GetString("WNMP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wnmp目录 的本地化字符串。
        /// </summary>
        public static string WNMP_DIRECTORY {
            get {
                return ResourceManager.GetString("WNMP_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wnmp选项 的本地化字符串。
        /// </summary>
        public static string WNMP_OPTIONS {
            get {
                return ResourceManager.GetString("WNMP_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wnmp版本：{CURRENTVERSION} 的本地化字符串。
        /// </summary>
        public static string WNMP_VERSION {
            get {
                return ResourceManager.GetString("WNMP_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定要更新吗？ 的本地化字符串。
        /// </summary>
        public static string WOULD_YOU_LIKE_TO_DOWNLOAD_THIS_UPDATE_QM {
            get {
                return ResourceManager.GetString("WOULD_YOU_LIKE_TO_DOWNLOAD_THIS_UPDATE_QM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是的 的本地化字符串。
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的版本： 的本地化字符串。
        /// </summary>
        public static string YOUR_VERSION_SC {
            get {
                return ResourceManager.GetString("YOUR_VERSION_SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的版本：{CURRENTVERSION}是最新的。 的本地化字符串。
        /// </summary>
        public static string YOUR_VERSION_VER_IS_UP_TO_DATE_DOT {
            get {
                return ResourceManager.GetString("YOUR_VERSION_VER_IS_UP_TO_DATE_DOT", resourceCulture);
            }
        }
    }
}
